{
 "title": "Python monitoring agent",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: v.defaultBucket, tag: \"hostname\")"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_metrics\")\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> map(fn: (r) => ({ devices: r[\"device\"] }))\n"
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net_interface_metrics\")\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"net_bytes_recv\" and r[\"_value\"] >0 )\n  |> map(fn: (r) => ({ device: r[\"interface\"] }))\n"
   },
   {
    "name": "container",
    "label": "Containers",
    "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_metrics\")\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"container_name\")\n  |> map(fn: (r) => ({ containers: r[\"_value\"] }))"
   },
   {
    "name": "images",
    "label": "Images",
    "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_image_metrics\")\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"image_name\")\n  |> map(fn: (r) => ({ containers: r[\"_value\"] }))"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ram summary",
     "type": "stat",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ram_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_total\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Total RAM\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ram_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_used\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Used RAM\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ram_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_free\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Free RAM\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ram_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_cached\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Cached RAM\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ram_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_buffers\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Buffered RAM\"}))\n  "
      }
     ]
    },
    {
     "title": "SWAP summary",
     "type": "stat",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swap_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_total\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Total SWAP\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swap_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_used\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Used SWAP\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swap_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_free\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Free SWAP\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_processors\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"No. of cores\"}))\n  "
      }
     ]
    },
    {
     "title": "Number of CPUs",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_processors\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"No. of cores\"}))\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "Performance overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "Host",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU speed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_current\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value * 1000000.0}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Frequency\"}))\n  "
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_1m\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"1m AVG utilization\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_5m\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"5m AVG utilization\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_15m\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"15m AVG utilization\"}))\n  "
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_utilization\")\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value}))\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"CPU utilization\"}))\n  "
      }
     ]
    },
    {
     "title": "SWAP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expression": "($B / $A) * 100", "type": "math" }
     ]
    },
    {
     "title": "RAM",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "($B / $A) * 100", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Docker overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of containers",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"container_state\")\n  |> filter(fn: (r) => r[\"_value\"] == \"exited\")\n  |> unique(column: \"container_id\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Exited containers\"}))\n  |> count()"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"container_state\")\n  |> filter(fn: (r) => r[\"_value\"] == \"running\")\n  |> unique(column: \"container_id\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Running containers\"}))\n  |> count()"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"container_state\")\n  |> filter(fn: (r) => r[\"_value\"] == \"created\")\n  |> unique(column: \"container_id\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Created containers\"}))\n  |> count()\n"
      }
     ]
    },
    {
     "title": "Number of containers",
     "type": "stat",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"container_state\")\n  |> unique(column: \"container_id\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Exited containers\"}))\n  |> count()"
      }
     ]
    },
    {
     "title": "Number of images",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"image_name\")\n  |> unique(column: \"image_id\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Number of images\"}))\n  |> count()\n"
      }
     ]
    },
    {
     "title": "Docker engine version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"docker_version\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Docker engine version\"}))\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk $disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_metrics\")\n  |> filter(fn: (r) => r[\"device\"] == ${disk:doublequote})\n  |> map(fn: (r) => ({_value: r[\"fs\"], _time: r._time, _field: \"Filesystem\"}))"
      }
     ]
    },
    {
     "title": "Mountpoint",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 2, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_metrics\")\n  |> filter(fn: (r) => r[\"device\"] == ${disk:doublequote})\n  |> map(fn: (r) => ({_value: r[\"mountpoint\"], _time: r._time, _field: \"Mountpoint\"}))"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_total_space\")\n  |> map(fn: (r) => ({_value: r[\"_value\"], _time: r._time, _field: \"Total space\"}))"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_used_space\")\n  |> map(fn: (r) => ({_value: r[\"_value\"], _time: r._time, _field: \"Used space\"}))"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_free_space\")\n  |> map(fn: (r) => ({_value: r[\"_value\"], _time: r._time, _field: \"Free space\"}))"
      }
     ]
    },
    {
     "title": "Block device",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_metrics\")\n  |> filter(fn: (r) => r[\"device\"] == ${disk:doublequote})\n  |> map(fn: (r) => ({_value: r[\"device\"], _time: r._time, _field: \"Block device\"}))"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expression": "($B / $A) * 100", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Network Interface $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Network interface utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net_interface_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"net_bytes_sent\")\n  |> filter(fn: (r) => r[\"interface\"] == ${interface:doublequote})\n  |> map(fn: (r) => ({_value: r[\"_value\"], _time: r._time, _field: \"Upload speed\"}))\n  |> derivative(unit: 1s)\n"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net_interface_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"net_bytes_recv\")\n  |> filter(fn: (r) => r[\"interface\"] == ${interface:doublequote})\n  |> map(fn: (r) => ({_value: r[\"_value\"], _time: r._time, _field: \"Download speed\"}))\n  |> derivative(unit: 1s)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Container - $container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "container",
   "collapsed": true,
   "panels": [
    {
     "title": "Container's memory usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "container_name = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"container_name\")\n  |> filter(fn: (r) => r[\"_value\"] == ${container:doublequote})\n  |> map(fn: (r) => ({ \"name\": r[\"_value\"], \"container_id\": r[\"container_id\"]}))\n  \n\ncontainer_memory_usage = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"container_memory_usage\")\n  |> map(fn: (r) => ({ \"memory_usage\": r[\"_value\"], time: r._time, \"container_id\": r[\"container_id\"]}))\n\njoined = join(\n  tables: {a: container_name, b: container_memory_usage},\n  on: [\"container_id\"]\n)\njoined\n  |> keep(columns: [\"name\", \"memory_usage\", \"container_id\", \"time\"])\n  |> map(fn: (r) => ({ \"RSS memory used\": r[\"memory_usage\"], time: r.time, \"name\": r[\"name\"]}))"
      }
     ]
    },
    {
     "title": "Container's network activity",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "query": "container_name = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"container_name\")\n  |> filter(fn: (r) => r[\"_value\"] == ${container:doublequote})\n  |> map(fn: (r) => ({ \"name\": r[\"_value\"], \"container_id\": r[\"container_id\"]}))\n  \ncontainer_network_rx = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"container_rx_bytes\")\n  |> map(fn: (r) => ({ \"rx_bytes\": r[\"_value\"], time: r._time, \"container_id\": r[\"container_id\"]}))\n  \njoined = join(tables: {a: container_name, b: container_network_rx}, on: [\"container_id\"])\njoined\n  |> sort(columns: [\"time\"])\n  |> keep(columns: [\"name\", \"rx_bytes\", \"time\"])\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"rx_bytes\"], timeColumn: \"time\")\n  |> map(fn: (r) => ({ \"Container download\": r[\"rx_bytes\"], _time: r.time, \"name\": r[\"name\"]}))"
      },
      {
       "query": "container_name = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"container_name\")\n  |> filter(fn: (r) => r[\"_value\"] == ${container:doublequote})\n  |> map(fn: (r) => ({ \"name\": r[\"_value\"], \"container_id\": r[\"container_id\"]}))\n  \ncontainer_network_tx = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"hostname\"] == ${host:doublequote})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"container_tx_bytes\")\n  |> map(fn: (r) => ({ \"tx_bytes\": r[\"_value\"], time: r._time, \"container_id\": r[\"container_id\"]}))\n  \njoined = join(tables: {a: container_name, b: container_network_tx}, on: [\"container_id\"])\njoined\n  |> sort(columns: [\"time\"])\n  |> keep(columns: [\"name\", \"tx_bytes\", \"time\"])\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"tx_bytes\"], timeColumn: \"time\")\n  |> map(fn: (r) => ({ \"Container upload\": r[\"tx_bytes\"], _time: r.time, \"name\": r[\"name\"]}))"
      }
     ]
    }
   ]
  }
 ]
}