name: Docker Image CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GHCR_TOKEN}}
    
    - name: 'Build Inventory Image'
      run: |
       username=${{github.actor}}
       export username="$username | awk '{print tolower($0)}'"
       export reponame=$(basename $(pwd))
       export tag=$(date +%d%m%Y%H%M)
       docker build ./docker/agent --tag $reponame:$tag
       docker tag $reponame:$tag $reponame:latest
       docker push ghcr.io/$username/:$tag
       docker push ghcr.io/$username/:latest

      
