name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GHCR_TOKEN}}

        - name: Get current date to use it as TAG
          run: | 
            echo "current=$(date +%d%m%Y%H%M)" >> $GITHUB_OUTPUT
          id: date

        - name: Build and push develop
          uses: docker/build-push-action@v4
          if: github.ref == 'refs/heads/develop'
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            context: ./docker/agent
            tags: |
              ghcr.io/szymonrysztof/python-monitoring-agent:develop-latest
              ghcr.io/szymonrysztof/python-monitoring-agent:${{ steps.date.outputs.current }}

        - name: Build and push master
          uses: docker/build-push-action@v4
          if: github.ref == 'refs/heads/master'
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            context: ./docker/agent
            tags: |
              ghcr.io/szymonrysztof/python-monitoring-agent:latest
